version: "3.8"

services:
  exrssbot:
    image: exrssbot:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/app
    working_dir: /app
    command: /bin/sh
